import { z } from 'zod';

/**
 * The connector layer (Phase 4 §3, FR-010).
 *
 * A common interface with per-partner configuration behind an adapter
 * boundary. **No university-specific conditional logic in the core** — the core
 * knows five connector *shapes*, and a partner is configuration, not a branch.
 *
 * The shapes differ in one way that matters more than any other: whether the
 * university can hand back a durable reference synchronously. An API connector
 * can. A portal handoff cannot, because the student has not finished signing in
 * yet. That difference is what `SubmissionOutcome` below encodes, and it is why
 * "submitted" is never a synonym for "the call returned".
 */
export const CONNECTOR_TYPES = [
  'api',
  'portal_handoff',
  'deep_link',
  'file_exchange',
  'operator_assisted',
] as const;

export type ConnectorType = (typeof CONNECTOR_TYPES)[number];

/** Shown to the student before they submit, so the route is never a surprise. */
export function connectorDescription(type: ConnectorType, institutionName: string): string {
  switch (type) {
    case 'api':
      return `${institutionName} receives applications directly from Modex Apply and confirms each one with their own reference number.`;
    case 'portal_handoff':
      return `We prepare everything, then hand you to ${institutionName}'s own portal to sign in and finish. Your application is not submitted until they confirm it.`;
    case 'deep_link':
      return `We prepare everything, then send you to ${institutionName}'s official application page with your details carried across. Your application is not submitted until they confirm it.`;
    case 'file_exchange':
      return `${institutionName} receives applications as a secure scheduled package. Confirmation comes back with their reference, usually within one working day.`;
    case 'operator_assisted':
      return `${institutionName} cannot yet receive applications automatically, so a named member of Modex staff submits this one to them on your behalf, under the consent you give below. Who did it and when is recorded permanently on this application.`;
  }
}

/**
 * Whether a connector can confirm receipt in the same call.
 *
 * The tracker's copy turns on this: for a synchronous connector, sitting in
 * `submitted_pending` for a minute means something is wrong; for a handoff, it
 * is the normal state of affairs and saying "something is wrong" would be a
 * lie. Same state, different sentence.
 */
export function isSynchronousConnector(type: ConnectorType): boolean {
  return type === 'api' || type === 'file_exchange';
}

/**
 * Operator-assisted is a **temporary exception**, and the type system is where
 * that is recorded rather than a policy document nobody reads. Every call site
 * that treats it like the others has to say so explicitly.
 */
export function requiresPermanentDisclosure(type: ConnectorType): boolean {
  return type === 'operator_assisted';
}

// ---------------------------------------------------------------------------
// The submission outcome
// ---------------------------------------------------------------------------

/**
 * What an adapter is allowed to say.
 *
 * A discriminated union rather than a status string plus optional fields,
 * because the one thing that must be impossible is an `accepted` outcome with
 * no external reference. Here that shape does not typecheck.
 */
export const SubmissionOutcomeSchema = z.discriminatedUnion('status', [
  z.object({
    status: z.literal('accepted'),
    /** The university's own durable reference. Never generated by Modex. */
    externalRef: z.string().min(1),
    receivedAt: z.iso.datetime(),
    /** Whatever the partner returned, kept verbatim as receipt evidence. */
    evidence: z.record(z.string(), z.unknown()).default({}),
  }),
  z.object({
    status: z.literal('handoff_required'),
    /** Where to send the student to finish. Confirmation arrives later. */
    continuationUrl: z.url(),
    /** Opaque token the partner will quote back, so the callback is attributable. */
    handoffRef: z.string().min(1),
    expiresAt: z.iso.datetime(),
  }),
  z.object({
    status: z.literal('queued'),
    /** Accepted for later delivery — a file exchange batch, not a receipt. */
    batchRef: z.string().min(1),
    expectedBy: z.iso.datetime(),
  }),
  z.object({
    status: z.literal('rejected'),
    /** The partner said no. Retrying will not change the answer. */
    code: z.string(),
    message: z.string(),
    fieldErrors: z.array(z.object({ field: z.string(), message: z.string() })).default([]),
  }),
  z.object({
    status: z.literal('retryable_failure'),
    /** A timeout, a 502, a connection reset. Try again with backoff. */
    reason: z.string(),
    retryAfterSeconds: z.number().int().positive().nullable().default(null),
  }),
]);

export type SubmissionOutcome = z.infer<typeof SubmissionOutcomeSchema>;

/**
 * **The receipt rule, as one function.**
 *
 * The only outcome that moves an application to `submitted` is `accepted` with
 * a non-empty reference. `queued` and `handoff_required` are progress, not
 * receipt; they leave the application in `submitted_pending` where the copy is
 * "Sending to …".
 */
export function isReceipt(
  outcome: SubmissionOutcome,
): outcome is Extract<SubmissionOutcome, { status: 'accepted' }> {
  return outcome.status === 'accepted' && outcome.externalRef.trim().length > 0;
}

export function isRetryable(outcome: SubmissionOutcome): boolean {
  return outcome.status === 'retryable_failure';
}

export const SUBMISSION_ATTEMPT_STATES = [
  'in_flight',
  'accepted',
  'awaiting_handoff',
  'queued',
  'rejected',
  'failed',
  'dead_lettered',
] as const;

export type SubmissionAttemptState = (typeof SUBMISSION_ATTEMPT_STATES)[number];

export function attemptStateFor(outcome: SubmissionOutcome): SubmissionAttemptState {
  switch (outcome.status) {
    case 'accepted':
      return 'accepted';
    case 'handoff_required':
      return 'awaiting_handoff';
    case 'queued':
      return 'queued';
    case 'rejected':
      return 'rejected';
    case 'retryable_failure':
      return 'failed';
  }
}

/**
 * Retry schedule. Exponential with a cap, and a deliberately small attempt
 * count: a university endpoint that has refused six times over about ten
 * minutes needs a human, not a seventh attempt.
 */
export const MAX_SUBMISSION_ATTEMPTS = 6;

export function retryDelaySeconds(attemptNo: number): number {
  return Math.min(2 ** attemptNo * 15, 900);
}

/** The sentence a student reads on a failed attempt, and the step after it. */
export function failureGuidance(outcome: SubmissionOutcome, institutionName: string): {
  what: string;
  next: string;
} {
  switch (outcome.status) {
    case 'rejected':
      return {
        what: `${institutionName} did not accept the application: ${outcome.message}`,
        next:
          outcome.fieldErrors.length > 0
            ? 'Fix the details listed below, then send it again.'
            : 'Open the application, check the details, then send it again.',
      };
    case 'retryable_failure':
      return {
        what: `We could not reach ${institutionName} (${outcome.reason}).`,
        next: 'We are retrying automatically. Nothing has been submitted, and you do not need to do anything yet.',
      };
    default:
      return {
        what: 'The submission did not complete.',
        next: 'We are looking into it. Your application has not been sent.',
      };
  }
}

// ---------------------------------------------------------------------------
// Inbound status events
// ---------------------------------------------------------------------------

/**
 * The statuses a university may report. Mapped to application states by the
 * core, so a partner's vocabulary never leaks into the state machine.
 */
export const INBOUND_STATUS_KINDS = [
  'received',
  'under_review',
  'more_info_required',
  'offer_made',
  'rejected',
  'withdrawn',
  'enrolled',
] as const;

export type InboundStatusKind = (typeof INBOUND_STATUS_KINDS)[number];

export const InboundStatusEventSchema = z.object({
  /** The partner's own event id. The idempotency key for inbound traffic. */
  providerEventId: z.string().min(1),
  /** Their reference, which is how the event finds its application. */
  externalRef: z.string().min(1),
  /**
   * The reference *Modex* gave them — a handoff token or a batch reference.
   *
   * Needed because an asynchronous connector confirms an application we do not
   * yet hold a university reference for: the very first event is the one that
   * tells us what their reference *is*, so it cannot also be the thing we look
   * the application up by. A portal handoff quotes this back from the
   * continuation URL; a file-exchange partner quotes the batch reference.
   */
  modexRef: z.string().min(1).optional(),
  kind: z.enum(INBOUND_STATUS_KINDS),
  occurredAt: z.iso.datetime(),
  /** Free-form partner detail, stored verbatim and never interpreted. */
  detail: z.record(z.string(), z.unknown()).default({}),
});

export type InboundStatusEvent = z.infer<typeof InboundStatusEventSchema>;

/**
 * The one place a partner's vocabulary becomes a Modex state.
 *
 * `received` maps to `submitted` and nothing else does: an inbound event is the
 * receipt for a connector that could not give one synchronously.
 */
export function stateForInboundStatus(kind: InboundStatusKind):
  | 'submitted'
  | 'under_review'
  | 'more_info'
  | 'offer'
  | 'rejected'
  | 'withdrawn'
  | 'enrolled' {
  switch (kind) {
    case 'received':
      return 'submitted';
    case 'under_review':
      return 'under_review';
    case 'more_info_required':
      return 'more_info';
    case 'offer_made':
      return 'offer';
    case 'rejected':
      return 'rejected';
    case 'withdrawn':
      return 'withdrawn';
    case 'enrolled':
      return 'enrolled';
  }
}

// ---------------------------------------------------------------------------
// Webhook signatures
// ---------------------------------------------------------------------------

/**
 * Inbound webhooks are signed, and the signature covers a timestamp.
 *
 * Without the timestamp in the signed material, a captured request is valid
 * forever and "replay-safe" means only "we store the event id" — which stops a
 * duplicate but not an attacker replaying a six-month-old `offer_made` at a
 * moment of their choosing. The event id and the window are both needed, and
 * they stop different things.
 */
export const WEBHOOK_TOLERANCE_SECONDS = 300;

/**
 * The signed material: timestamp, a separator, then the raw body exactly as it
 * arrived. Signing a re-serialised body would mean a partner's key ordering
 * could change the signature without changing the request.
 *
 * Signing and verification themselves live in `@modex/contracts/node` — they
 * need `node:crypto`, and this module is compiled into browser bundles.
 */
export function webhookSigningPayload(timestamp: string, rawBody: string): string {
  return `${timestamp}.${rawBody}`;
}

/**
 * Per-partner poll budget for connectors with no webhooks. Rate limiting is a
 * property of the partner's configuration, not of our convenience: a university
 * that asks for one call a minute gets one call a minute.
 */
export const DEFAULT_POLL_INTERVAL_SECONDS = 900;
export const MIN_POLL_INTERVAL_SECONDS = 60;
